# Generated by Django 4.2.4 on 2023-08-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_exercise_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(choices=[('V', 'Valor'), ('M', 'Mystic'), ('I', 'Instinct')], default='V', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(verbose_name='training date'),
        ),
    ]
