# Generated by Django 4.2.4 on 2023-08-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_trainer_alter_exercise_options_alter_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainers',
            field=models.ManyToManyField(to='main_app.trainer'),
        ),
    ]
